/* Audrey Closet v13.22 Draw Studio dev9
 * Live tools: Pencil, Pen, Sharpie, Highlighter, stroke Eraser.
 * Removes floating cursor. Removes Done button: tool selection controls Draw mode.
 * Tap selected tool again to deselect and restore normal Board touch/scroll.
 */
(function(){
  'use strict';

  const ROOT_ID='drawStudioDev9';
  const STYLE_ID='drawStudioDev9Styles';
  const MAX_DRAW_UNDO=50;
  const TOOLS=[
    ['line','Line','╱'],['arrow','Arrow','➜'],['pencil','Pencil','✎'],['pen','Pen','✒'],['sharpie','Sharpie','▬'],['highlighter','Highlight','▰'],['eraser','Eraser','⌫']
  ];
  const LIVE_TOOLS=new Set(['pencil','pen','sharpie','highlighter','eraser']);
  const TOOL_DEFAULTS={
    line:{thickness:3,color:'#30343b',opacity:1},arrow:{thickness:3,color:'#30343b',opacity:1},
    pencil:{thickness:2,color:'#6b6b6b',opacity:1},pen:{thickness:4,color:'#2457c5',opacity:1},
    sharpie:{thickness:9,color:'#111111',opacity:1},highlighter:{thickness:16,color:'#fff44f',opacity:.38},
    eraser:{thickness:18,color:'#ffffff',opacity:1}
  };
  const toolSettings={};
  Object.keys(TOOL_DEFAULTS).forEach(tool=>toolSettings[tool]={...TOOL_DEFAULTS[tool]});
  const state={tool:'pencil',thickness:2,color:'#6b6b6b',lineStyle:'solid',arrowEnds:'single',drawMode:false};
  const drawHistory=[];
  let activeStroke=null;
  let activeErase=null;
  let rendererInstalled=false;
  let boardListenersInstalled=false;

  function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]);}
  function toolOpacity(tool){return TOOL_DEFAULTS[tool]?.opacity??1;}
  function toolIsLive(tool=state.tool){return !!tool&&LIVE_TOOLS.has(tool);}
  function rememberCurrentTool(){if(state.tool&&toolSettings[state.tool]){toolSettings[state.tool].thickness=state.thickness;toolSettings[state.tool].color=state.color;}}
  function loadToolSettings(tool){const saved=toolSettings[tool]||TOOL_DEFAULTS[tool]||{thickness:3,color:'#30343b'};state.thickness=saved.thickness;state.color=saved.color;}
  function cloneItem(item){return JSON.parse(JSON.stringify(item));}

  function installStyles(){
    if(document.getElementById(STYLE_ID))return;
    const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
      .screen[data-screen="outfits"] #${ROOT_ID}{display:grid!important;gap:6px;margin:0 0 6px;padding:7px 9px;border:1px solid rgba(102,113,90,.18);border-radius:10px;background:rgba(238,240,232,.68);color:#5d6657;font:600 10px/1.2 var(--sans,system-ui,sans-serif)}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-clean-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.screen[data-screen="outfits"] #${ROOT_ID} .draw-clean-head small{font:700 9px/1 var(--sans,system-ui,sans-serif);opacity:.72}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-strip{display:flex!important;gap:5px;max-width:100%;overflow-x:auto;overflow-y:hidden;padding:1px 0 3px;scrollbar-width:none;-webkit-overflow-scrolling:touch;touch-action:pan-x}.screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-strip::-webkit-scrollbar{display:none}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-btn{appearance:none;-webkit-appearance:none;display:grid!important;place-items:center;grid-template-rows:24px auto;gap:2px;flex:0 0 58px;min-width:58px;height:48px;padding:4px 3px;border:1px solid rgba(102,113,90,.22);border-radius:9px;background:rgba(255,255,255,.62);color:#5b6356;font:700 8px/1 var(--sans,system-ui,sans-serif);-webkit-tap-highlight-color:transparent}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-btn .draw-tool-icon{display:grid;place-items:center;width:24px;height:24px;font:700 16px/1 var(--sans,system-ui,sans-serif)}.screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-btn.active{border-color:#66715a;background:rgba(102,113,90,.15);color:#4f5949;box-shadow:inset 0 0 0 1px rgba(102,113,90,.18)}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-control-row{display:grid;grid-template-columns:minmax(116px,1.35fr) 42px auto;gap:5px;align-items:center}.screen[data-screen="outfits"] #${ROOT_ID} .draw-thickness{display:grid;grid-template-columns:auto minmax(60px,1fr) 24px;gap:5px;align-items:center;min-width:0}.screen[data-screen="outfits"] #${ROOT_ID} .draw-control-label{font:800 8px/1 var(--sans,system-ui,sans-serif);text-transform:uppercase;letter-spacing:.05em;color:#786f64;white-space:nowrap}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-thickness input[type="range"]{width:100%;min-width:0;margin:0;accent-color:#66715a}.screen[data-screen="outfits"] #${ROOT_ID} .draw-thickness-value{display:grid;place-items:center;min-width:24px;height:24px;border-radius:7px;background:rgba(255,255,255,.65);font:800 9px/1 var(--sans,system-ui,sans-serif);color:#56604f}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-color-wrap{position:relative;display:block;width:42px;height:32px;border:1px solid rgba(102,113,90,.20);border-radius:9px;background:var(--draw-color,#6b6b6b);overflow:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.22)}.screen[data-screen="outfits"] #${ROOT_ID} .draw-color-wrap input[type="color"]{position:absolute;inset:0;width:100%;height:100%;margin:0;padding:0;border:0;opacity:0;cursor:pointer}.screen[data-screen="outfits"] #${ROOT_ID}.eraser-selected .draw-color-wrap,.screen[data-screen="outfits"] #${ROOT_ID}.eraser-selected .draw-segment{opacity:.35;pointer-events:none}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-segment{display:flex;gap:3px;justify-content:flex-end}.screen[data-screen="outfits"] #${ROOT_ID} .draw-seg-btn,.screen[data-screen="outfits"] #${ROOT_ID} .draw-undo-btn{appearance:none;-webkit-appearance:none;height:32px;padding:0 8px;border:1px solid rgba(102,113,90,.20);border-radius:9px;background:rgba(255,255,255,.62);color:#666057;font:800 8px/1 var(--sans,system-ui,sans-serif);white-space:nowrap}.screen[data-screen="outfits"] #${ROOT_ID} .draw-seg-btn.active{border-color:#66715a;background:rgba(102,113,90,.15);color:#4f5949}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-secondary-row{display:flex;gap:6px;align-items:center;justify-content:space-between;min-height:34px}.screen[data-screen="outfits"] #${ROOT_ID} .draw-status-wrap{display:grid;gap:2px;min-width:0}.screen[data-screen="outfits"] #${ROOT_ID} .draw-tool-status{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:600 9px/1.25 var(--sans,system-ui,sans-serif);color:#756d63}.screen[data-screen="outfits"] #${ROOT_ID} .draw-mode-hint{font:700 8px/1.2 var(--sans,system-ui,sans-serif);color:#81786d}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-undo-btn{display:inline-flex;align-items:center;gap:4px;justify-content:center;min-width:60px}.screen[data-screen="outfits"] #${ROOT_ID} .draw-undo-btn:disabled{opacity:.35}.screen[data-screen="outfits"] #${ROOT_ID} .draw-undo-count{display:grid;place-items:center;min-width:16px;height:16px;padding:0 4px;border-radius:999px;background:rgba(102,113,90,.12);font-size:7px}
      .screen[data-screen="outfits"] #${ROOT_ID} .draw-arrow-settings{display:flex;gap:3px;align-items:center}.screen[data-screen="outfits"] #${ROOT_ID} .draw-arrow-settings.hidden{display:none}.screen[data-screen="outfits"] .decorate-studio-panel[data-decorate-group="draw"] .decorate-draw-current{display:none!important}
      #outfitBoard.draw-dev9-active{touch-action:none!important;cursor:crosshair}#outfitBoard.draw-dev9-eraser{cursor:cell}#outfitBoard .draw-live-overlay-dev9{position:absolute;inset:0;width:100%;height:100%;z-index:2147483000;pointer-events:none;overflow:visible}.board-piece .drawing-svg-dev9{display:block;width:100%;height:100%;overflow:visible;pointer-events:none}
      @media (max-width:430px){.screen[data-screen="outfits"] #${ROOT_ID} .draw-control-row{grid-template-columns:minmax(104px,1fr) 38px auto}.screen[data-screen="outfits"] #${ROOT_ID} .draw-color-wrap{width:38px}.screen[data-screen="outfits"] #${ROOT_ID} .draw-seg-btn{padding:0 6px;font-size:7px}.screen[data-screen="outfits"] #${ROOT_ID} .draw-undo-btn{min-width:54px;padding:0 6px}}
    `;document.head.appendChild(s);
  }

  function installDrawingRenderer(){
    if(rendererInstalled)return true;if(typeof boardItemContent!=='function'||typeof normalizeBoardItem!=='function')return false;
    const originalContent=boardItemContent;boardItemContent=function(b){if(b&&b.kind==='drawing'&&b.drawingType==='freeform'){const w=Math.max(1,Number(b.w)||1),h=Math.max(1,Number(b.h)||1),color=esc(b.strokeColor||TOOL_DEFAULTS[b.tool]?.color||'#6b6b6b'),width=Math.max(1,Number(b.strokeWidth)||2),opacity=Math.max(0,Math.min(1,Number(b.opacity??1))),dash=b.strokeStyle==='dotted'?`${Math.max(1,width*.6)} ${Math.max(2,width*2.2)}`:'';return `<svg class="drawing-svg-dev9" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><polyline points="${esc(b.points||'')}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linecap="round" stroke-linejoin="round"${dash?` stroke-dasharray="${dash}"`:''} opacity="${opacity}" vector-effect="non-scaling-stroke"/></svg>`;}return originalContent(b);};
    const originalNormalize=normalizeBoardItem;normalizeBoardItem=function(b){b=originalNormalize(b);if(b&&b.kind==='drawing'){b.drawingType=b.drawingType||'freeform';b.tool=b.tool||'pencil';b.strokeColor=b.strokeColor||TOOL_DEFAULTS[b.tool]?.color||'#6b6b6b';b.strokeWidth=Math.max(1,Number(b.strokeWidth)||TOOL_DEFAULTS[b.tool]?.thickness||2);b.strokeStyle=b.strokeStyle==='dotted'?'dotted':'solid';b.opacity=Math.max(0,Math.min(1,Number(b.opacity??toolOpacity(b.tool))));b.points=String(b.points||'');}return b;};rendererInstalled=true;return true;
  }

  function pointOnBoard(board,e){const r=board.getBoundingClientRect(),sx=r.width?board.clientWidth/r.width:1,sy=r.height?board.clientHeight/r.height:1;return{x:Math.max(0,Math.min(board.clientWidth,(e.clientX-r.left)*sx)),y:Math.max(0,Math.min(board.clientHeight,(e.clientY-r.top)*sy))};}
  function ensureOverlay(board){let svg=board.querySelector('.draw-live-overlay-dev9');if(svg)svg.remove();svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','draw-live-overlay-dev9');svg.setAttribute('viewBox',`0 0 ${Math.max(1,board.clientWidth)} ${Math.max(1,board.clientHeight)}`);svg.setAttribute('preserveAspectRatio','none');const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('fill','none');line.setAttribute('stroke',state.color);line.setAttribute('stroke-width',String(state.thickness));line.setAttribute('stroke-linecap','round');line.setAttribute('stroke-linejoin','round');line.setAttribute('opacity',String(toolOpacity(state.tool)));if(state.lineStyle==='dotted')line.setAttribute('stroke-dasharray',`${Math.max(1,state.thickness*.6)} ${Math.max(2,state.thickness*2.2)}`);svg.appendChild(line);board.appendChild(svg);return{svg,line};}
  function updateLiveStroke(){if(activeStroke)activeStroke.line.setAttribute('points',activeStroke.points.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' '));}
  function parsePoints(item){return String(item.points||'').trim().split(/\s+/).map(pair=>pair.split(',').map(Number)).filter(p=>p.length===2&&p.every(Number.isFinite)).map(([x,y])=>({x:(Number(item.x)||0)+x,y:(Number(item.y)||0)+y}));}
  function pointSegmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(p.x-a.x,p.y-a.y);let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l2;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));}
  function drawingHit(item,p,radius){if(!item||item.kind!=='drawing')return false;const pts=parsePoints(item);if(!pts.length)return false;const tolerance=radius+(Number(item.strokeWidth)||2)/2+3;if(pts.length===1)return Math.hypot(p.x-pts[0].x,p.y-pts[0].y)<=tolerance;for(let i=1;i<pts.length;i++)if(pointSegmentDistance(p,pts[i-1],pts[i])<=tolerance)return true;return false;}

  function pushHistory(action){drawHistory.push(action);if(drawHistory.length>MAX_DRAW_UNDO)drawHistory.splice(0,drawHistory.length-MAX_DRAW_UNDO);syncUndo();}
  function syncUndo(root=document.getElementById(ROOT_ID)){if(!root)return;const b=root.querySelector('.draw-undo-btn'),c=root.querySelector('.draw-undo-count');if(b)b.disabled=!drawHistory.length;if(c)c.textContent=String(drawHistory.length);}
  function undoLast(){if(typeof boardItems==='undefined'||typeof drawBoard!=='function'||!drawHistory.length)return;const action=drawHistory.pop();if(action.type==='add'){const i=boardItems.findIndex(x=>x&&x.uid===action.uid);if(i>=0)boardItems.splice(i,1);}else if(action.type==='erase'){action.items.forEach(entry=>{if(!boardItems.some(x=>x&&x.uid===entry.item.uid))boardItems.push(cloneItem(entry.item));});}drawBoard();syncUndo();}

  function eraseAt(board,p){if(typeof boardItems==='undefined')return false;const radius=Math.max(5,state.thickness/2);let changed=false;for(let i=boardItems.length-1;i>=0;i--){const item=boardItems[i];if(!drawingHit(item,p,radius))continue;if(activeErase&&!activeErase.removed.some(x=>x.item.uid===item.uid))activeErase.removed.push({item:cloneItem(item),index:i});boardItems.splice(i,1);changed=true;}if(changed&&typeof drawBoard==='function')drawBoard();return changed;}

  function begin(board,e){if(!state.drawMode||!toolIsLive()||e.button>0)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();const p=pointOnBoard(board,e);try{board.setPointerCapture(e.pointerId)}catch(_){}if(state.tool==='eraser'){activeErase={pointerId:e.pointerId,removed:[]};eraseAt(board,p);return;}const overlay=ensureOverlay(board);activeStroke={pointerId:e.pointerId,points:[p],svg:overlay.svg,line:overlay.line,tool:state.tool,thickness:state.thickness,color:state.color,lineStyle:state.lineStyle,opacity:toolOpacity(state.tool)};updateLiveStroke();}
  function move(board,e){if(activeErase&&e.pointerId===activeErase.pointerId){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();eraseAt(board,pointOnBoard(board,e));return;}if(!activeStroke||e.pointerId!==activeStroke.pointerId)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();const p=pointOnBoard(board,e),last=activeStroke.points[activeStroke.points.length-1],dx=p.x-last.x,dy=p.y-last.y;if(dx*dx+dy*dy<1.5)return;activeStroke.points.push(p);updateLiveStroke();}
  function finish(board,e,cancelled){if(activeErase&&e.pointerId===activeErase.pointerId){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();const gesture=activeErase;activeErase=null;try{board.releasePointerCapture(e.pointerId)}catch(_){}if(!cancelled&&gesture.removed.length)pushHistory({type:'erase',items:gesture.removed});return;}if(!activeStroke||e.pointerId!==activeStroke.pointerId)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();const stroke=activeStroke;activeStroke=null;try{board.releasePointerCapture(e.pointerId)}catch(_){}stroke.svg?.remove();if(cancelled)return;if(stroke.points.length===1){const p=stroke.points[0];stroke.points.push({x:p.x+.01,y:p.y+.01});}if(typeof boardItems==='undefined'||typeof id!=='function'||typeof nextZ!=='function'||typeof drawBoard!=='function')return;const pad=Math.max(3,stroke.thickness*1.5),xs=stroke.points.map(p=>p.x),ys=stroke.points.map(p=>p.y),minX=Math.max(0,Math.min(...xs)-pad),minY=Math.max(0,Math.min(...ys)-pad),maxX=Math.min(board.clientWidth,Math.max(...xs)+pad),maxY=Math.min(board.clientHeight,Math.max(...ys)+pad),w=Math.max(2,maxX-minX),h=Math.max(2,maxY-minY),relative=stroke.points.map(p=>`${(p.x-minX).toFixed(1)},${(p.y-minY).toFixed(1)}`).join(' '),uid=id();boardItems.push({uid,kind:'drawing',drawingType:'freeform',tool:stroke.tool,strokeColor:stroke.color,strokeWidth:stroke.thickness,strokeStyle:stroke.lineStyle,opacity:stroke.opacity,points:relative,x:minX,y:minY,w,h,rotation:0,z:nextZ()});pushHistory({type:'add',uid});if(typeof selectedBoardUid!=='undefined')selectedBoardUid=null;drawBoard();}
  function cancelActive(){activeStroke?.svg?.remove();activeStroke=null;activeErase=null;}
  function installBoardListeners(){if(boardListenersInstalled)return true;const board=document.getElementById('outfitBoard');if(!board)return false;board.addEventListener('pointerdown',e=>begin(board,e),true);board.addEventListener('pointermove',e=>move(board,e),true);board.addEventListener('pointerup',e=>finish(board,e,false),true);board.addEventListener('pointercancel',e=>finish(board,e,true),true);boardListenersInstalled=true;return true;}

  function drawTabIsActive(){const tab=document.querySelector('.decorate-studio-tab[data-decorate-group="draw"]'),panel=document.querySelector('.decorate-studio-panel[data-decorate-group="draw"]');return !!tab&&tab.classList.contains('active')&&!!panel&&panel.classList.contains('active');}
  function applyMode(){const active=state.drawMode&&toolIsLive()&&drawTabIsActive(),board=document.getElementById('outfitBoard');if(board){board.classList.toggle('draw-dev9-active',active);board.classList.toggle('draw-dev9-eraser',active&&state.tool==='eraser');}if(!active)cancelActive();}
  function sync(root){root.classList.toggle('eraser-selected',state.tool==='eraser');root.querySelectorAll('.draw-tool-btn').forEach(btn=>{const a=btn.dataset.drawTool===state.tool;btn.classList.toggle('active',a);btn.setAttribute('aria-pressed',a?'true':'false');});root.querySelectorAll('[data-line-style]').forEach(btn=>{const a=btn.dataset.lineStyle===state.lineStyle;btn.classList.toggle('active',a);btn.setAttribute('aria-pressed',a?'true':'false');});const slider=root.querySelector('#drawThicknessDev9'),val=root.querySelector('.draw-thickness-value'),color=root.querySelector('#drawColorDev9'),wrap=root.querySelector('.draw-color-wrap');if(slider)slider.value=String(state.thickness);if(val)val.textContent=String(state.thickness);if(color)color.value=state.color;if(wrap)wrap.style.setProperty('--draw-color',state.color);const arrow=root.querySelector('.draw-arrow-settings');if(arrow)arrow.classList.toggle('hidden',state.tool!=='arrow');const match=TOOLS.find(([id])=>id===state.tool),status=root.querySelector('.draw-tool-status'),hint=root.querySelector('.draw-mode-hint');if(status){if(!state.tool)status.textContent='No tool selected';else if(state.tool==='eraser')status.textContent=`Eraser · ${state.thickness}px · stroke erase`;else{const opacity=state.tool==='highlighter'?' · 38% opacity':'';status.textContent=`${match?match[1]:state.tool} · ${state.thickness}px · ${state.lineStyle}${opacity}`;}}if(hint){if(!state.tool)hint.textContent='Board touch/scroll is normal · tap a tool to draw';else if(state.tool==='eraser')hint.textContent='Drag across drawing strokes to erase · Undo restores the gesture';else if(toolIsLive())hint.textContent=drawTabIsActive()?'Ready to draw · tap selected tool again to deselect':'Tool remembered for next Draw visit';else hint.textContent='This tool is UI-only in dev9';}syncUndo(root);applyMode();}
  function exitMode(){state.drawMode=false;cancelActive();const root=document.getElementById(ROOT_ID);if(root)sync(root);else applyMode();}
  function enterMode(){state.drawMode=toolIsLive()&&drawTabIsActive();const root=document.getElementById(ROOT_ID);if(root)sync(root);else applyMode();}

  function buildRoot(){const root=document.createElement('div');root.id=ROOT_ID;root.innerHTML=`
    <div class="draw-clean-head"><span>Draw Studio</span><small>dev9 · Eraser + tool toggle</small></div>
    <div class="draw-tool-strip" role="toolbar" aria-label="Draw tools">${TOOLS.map(([id,label,icon])=>`<button type="button" class="draw-tool-btn" data-draw-tool="${esc(id)}" aria-pressed="false"><span class="draw-tool-icon" aria-hidden="true">${icon}</span><span>${esc(label)}</span></button>`).join('')}</div>
    <div class="draw-control-row"><label class="draw-thickness"><span class="draw-control-label">Size</span><input id="drawThicknessDev9" type="range" min="1" max="30" step="1" value="2" aria-label="Draw thickness"><span class="draw-thickness-value">2</span></label><label class="draw-color-wrap" aria-label="Draw color"><input id="drawColorDev9" type="color" value="#6b6b6b"></label><div class="draw-segment" role="group" aria-label="Line style"><button type="button" class="draw-seg-btn" data-line-style="solid" aria-pressed="true">Solid</button><button type="button" class="draw-seg-btn" data-line-style="dotted" aria-pressed="false">Dotted</button></div></div>
    <div class="draw-secondary-row"><div class="draw-status-wrap"><div class="draw-tool-status" aria-live="polite"></div><div class="draw-mode-hint"></div></div><div class="draw-arrow-settings hidden" role="group" aria-label="Arrow ends"><span class="draw-control-label">Arrow</span><button type="button" class="draw-seg-btn" data-arrow-ends="single">Single</button><button type="button" class="draw-seg-btn" data-arrow-ends="double">Double</button></div><button type="button" class="draw-undo-btn" disabled>↶ Undo <span class="draw-undo-count">0</span></button></div>`;
    root.querySelectorAll('.draw-tool-btn').forEach(btn=>btn.addEventListener('click',()=>{const next=btn.dataset.drawTool;if(state.tool===next){rememberCurrentTool();state.tool=null;state.drawMode=false;}else{rememberCurrentTool();state.tool=next;loadToolSettings(next);state.drawMode=toolIsLive(next)&&drawTabIsActive();}sync(root);}));
    root.querySelector('#drawThicknessDev9')?.addEventListener('input',e=>{state.thickness=Math.max(1,Math.min(30,Number(e.target.value)||1));rememberCurrentTool();sync(root);});
    root.querySelector('#drawColorDev9')?.addEventListener('input',e=>{state.color=e.target.value||TOOL_DEFAULTS[state.tool]?.color||'#6b6b6b';rememberCurrentTool();sync(root);});
    root.querySelectorAll('[data-line-style]').forEach(btn=>btn.addEventListener('click',()=>{state.lineStyle=btn.dataset.lineStyle||'solid';sync(root);}));root.querySelector('.draw-undo-btn')?.addEventListener('click',undoLast);sync(root);return root;}

  function install(){installStyles();installDrawingRenderer();installBoardListeners();const panel=document.querySelector('.decorate-studio-panel[data-decorate-group="draw"]');if(!panel)return false;const content=panel.querySelector('.decorate-studio-content')||panel;let root=document.getElementById(ROOT_ID);if(root&&content.contains(root)){sync(root);return true;}if(root)root.remove();root=buildRoot();content.prepend(root);return true;}
  function scheduleInstallAndEnter(){requestAnimationFrame(()=>requestAnimationFrame(()=>{install();enterMode();}));}
  function start(){loadToolSettings('pencil');install();exitMode();document.addEventListener('click',e=>{const target=e.target;if(!(target instanceof Element))return;const tab=target.closest('.decorate-studio-tab[data-decorate-group]');if(tab){if(tab.dataset.decorateGroup==='draw')scheduleInstallAndEnter();else exitMode();return;}const insideDraw=target.closest(`#${ROOT_ID}, #outfitBoard, .decorate-studio-tab[data-decorate-group="draw"]`);if(!insideDraw)exitMode();if(target.closest?.('#decorateToggle'))window.setTimeout(install,0);},true);document.addEventListener('click',()=>setTimeout(()=>{if(!drawTabIsActive())exitMode();},0),false);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
